name: Test & Deploy
run-name: ${{ github.actor }} is testing & deploy
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Build
        run: docker compose -f docker-compose.test.yml build
      - name: Run tests
        run: docker compose -f docker-compose.test.yml up \
             --abort-on-container-exit \
             --exit-code-from app
      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: htmlcov
          path: htmlcov/
      - name: Cleanup
        if: always()
        run: docker compose -f docker-compose.test.yml down -v

